#-------------------------------------------------------------------------------
#System specifications for Appveyor
#-------------------------------------------------------------------------------

environment:
  matrix:
    - PYTHON_VERSION: "3.8"
      MINICONDA: "C:\\Miniconda3-x64"

install:
  - 'SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%'
  - conda config --set always_yes yes
  - conda config --prepend channels conda-forge
  - conda config --set channel_priority strict

#-----------------------------------------------------------------------------
# Create conda environment
#-----------------------------------------------------------------------------
  - conda create -n test python=%PYTHON_VERSION% rasterio scipy xarray netcdf4 dask
  - activate test

#-------------------------------------------------------------------------------
# Install rioxarray
#-------------------------------------------------------------------------------
  - python -m pip install -e .[all]

build: false

test_script:
  - python -m pytest --cov-report term-missing --cov=rioxarray
