# Configuration file for creating a Conda Environment with dependencies needed for rioxarray.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f environment.yml

name: rioxarray
channels:
- conda-forge
dependencies:
- python=3.12  # To align with pre-commit requirements
- rasterio
- libgdal-netcdf
- libgdal-hdf4
- libgdal-hdf5
- scipy
- xarray
- netcdf4
- dask
