# Configuration file for creating a Conda Environment with dependencies needed for rioxarray.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f environment.yml

name: rioxarray
channels:
- conda-forge
- defaults
dependencies:
- python
- rasterio
- scipy
- xarray
- netcdf4
- dask
